/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client.login_register_design;

import client.signup.SignupInterface;
import database.MyConnection;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import server.SignupImplement;


/**
 *
 * @author Pooja
 */
public class SignupForm extends javax.swing.JFrame {

    /**
     * Creates new form SignupForm
     */
    
    // create a variable to set the image path in it
    String image_path = null;
    public SignupForm() {
        initComponents();
        
        //center the form
        this.setLocationRelativeTo(null);
        
        //create a yellow border for the jpanel_title
        // 0 border in the top 
        Border jpanel_title_border = BorderFactory.createMatteBorder(0, 1, 1, 1, Color.yellow);
        //set the border of the jpanel_title
        jPanel_title.setBorder(jpanel_title_border);
        
        //create an orange border for the global panel
        Border global_panel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.orange);
        jPanel1.setBorder(global_panel_border);
        
        //create a black border dor the close & minimize jlabels
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimize.setBorder(label_border);
        jLabel_close.setBorder(label_border);
        
        //create a button group for the radiobuttons
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButton_Male);
        bg.add(jRadioButton_Female);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel_title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jLabel_confirm_password = new javax.swing.JLabel();
        jLabel_email_id = new javax.swing.JLabel();
        jLabel1_dob = new javax.swing.JLabel();
        jLabel_phone_no = new javax.swing.JLabel();
        jLabel1_address = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jTextField_Email_Id = new javax.swing.JTextField();
        jTextField_Phone_No = new javax.swing.JTextField();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jPasswordField_Confirm = new javax.swing.JPasswordField();
        jButton_Signup = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jTextField_Login = new javax.swing.JTextField();
        jCheckBox_Password = new javax.swing.JCheckBox();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Address = new javax.swing.JTextArea();
        jLabel1_dob1 = new javax.swing.JLabel();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jLabel_image = new javax.swing.JLabel();
        jButton_Select_Image = new javax.swing.JButton();
        jLabel_Image_Path = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jPanel_title.setBackground(new java.awt.Color(51, 204, 0));
        jPanel_title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(153, 153, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Welcome to Signup Form");

        jLabel_minimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_minimize.setText(" -");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });

        jLabel_close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_close.setText(" X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close)
                .addGap(3, 3, 3))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addGroup(jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_minimize)
                    .addComponent(jLabel_close))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_username.setForeground(new java.awt.Color(255, 102, 51));
        jLabel_username.setText("username*");

        jLabel_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_password.setForeground(new java.awt.Color(255, 102, 51));
        jLabel_password.setText("password*");

        jLabel_confirm_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_confirm_password.setForeground(new java.awt.Color(255, 102, 51));
        jLabel_confirm_password.setText("confirm password*");

        jLabel_email_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_email_id.setForeground(new java.awt.Color(255, 102, 51));
        jLabel_email_id.setText("email id*");

        jLabel1_dob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1_dob.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1_dob.setText("D.O.B.*");

        jLabel_phone_no.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_phone_no.setForeground(new java.awt.Color(255, 102, 51));
        jLabel_phone_no.setText("Phone No.*");

        jLabel1_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1_address.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1_address.setText("Address*");

        jTextField_Username.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Username.setText("username");
        jTextField_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusLost(evt);
            }
        });
        jTextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsernameActionPerformed(evt);
            }
        });

        jTextField_Email_Id.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Email_Id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Email_Id.setText("email_id");
        jTextField_Email_Id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_Email_IdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_Email_IdFocusLost(evt);
            }
        });
        jTextField_Email_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Email_IdActionPerformed(evt);
            }
        });

        jTextField_Phone_No.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Phone_No.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Phone_No.setText("9999999999");
        jTextField_Phone_No.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_Phone_NoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_Phone_NoFocusLost(evt);
            }
        });
        jTextField_Phone_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Phone_NoActionPerformed(evt);
            }
        });
        jTextField_Phone_No.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Phone_NoKeyTyped(evt);
            }
        });

        jPasswordField_Password.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField_Password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField_Password.setText("password");
        jPasswordField_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_PasswordFocusLost(evt);
            }
        });

        jPasswordField_Confirm.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField_Confirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField_Confirm.setText("password");
        jPasswordField_Confirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_ConfirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_ConfirmFocusLost(evt);
            }
        });

        jButton_Signup.setBackground(new java.awt.Color(0, 153, 255));
        jButton_Signup.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_Signup.setForeground(new java.awt.Color(204, 204, 204));
        jButton_Signup.setText("Sign Up");
        jButton_Signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_SignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_SignupMouseExited(evt);
            }
        });
        jButton_Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SignupActionPerformed(evt);
            }
        });

        jButton_Cancel.setBackground(new java.awt.Color(255, 51, 51));
        jButton_Cancel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_Cancel.setForeground(new java.awt.Color(204, 204, 204));
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_CancelMouseExited(evt);
            }
        });
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jTextField_Login.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Login.setForeground(new java.awt.Color(0, 102, 255));
        jTextField_Login.setText("account already exists? Click here to Login");
        jTextField_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_LoginMouseClicked(evt);
            }
        });
        jTextField_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LoginActionPerformed(evt);
            }
        });

        jCheckBox_Password.setBackground(new java.awt.Color(204, 204, 204));
        jCheckBox_Password.setForeground(new java.awt.Color(255, 51, 51));
        jCheckBox_Password.setText("see pass");
        jCheckBox_Password.setToolTipText("");
        jCheckBox_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_PasswordActionPerformed(evt);
            }
        });

        jDateChooser.setBackground(new java.awt.Color(204, 204, 204));
        jDateChooser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextArea_Address.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea_Address.setColumns(20);
        jTextArea_Address.setRows(5);
        jTextArea_Address.setText("Permanent Address\n");
        jTextArea_Address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextArea_AddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea_AddressFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea_Address);

        jLabel1_dob1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1_dob1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1_dob1.setText("Gender*");

        jRadioButton_Male.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Male.setSelected(true);
        jRadioButton_Male.setText("Male");

        jRadioButton_Female.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Female.setText("Female");
        jRadioButton_Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_FemaleActionPerformed(evt);
            }
        });

        jLabel_image.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_image.setForeground(new java.awt.Color(255, 102, 51));
        jLabel_image.setText("Image");

        jButton_Select_Image.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Select_Image.setText("Select image");
        jButton_Select_Image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Select_ImageActionPerformed(evt);
            }
        });

        jLabel_Image_Path.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_Image_Path.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Image_Path.setText("image path");
        jLabel_Image_Path.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextField1.setBackground(new java.awt.Color(240, 240, 240));
        jTextField1.setForeground(new java.awt.Color(204, 0, 0));
        jTextField1.setText("* Fields are mandatory fields and can't be empty");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_confirm_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_email_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_phone_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1_address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1_dob1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_Username)
                                    .addComponent(jTextField_Email_Id)
                                    .addComponent(jTextField_Phone_No, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(jPasswordField_Confirm)
                                    .addComponent(jPasswordField_Password))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox_Password))
                            .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_Signup)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton_Male)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_Female))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton_Select_Image)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Image_Path, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_username, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox_Password)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_email_id, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Email_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Phone_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_dob1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_Male)
                    .addComponent(jRadioButton_Female))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Select_Image)
                    .addComponent(jLabel_Image_Path))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1_address, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_PasswordActionPerformed
        // TODO add your handling code here:

        if(jCheckBox_Password.isSelected()){
            jPasswordField_Password.setEchoChar((char)0);
        }else{
            jPasswordField_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox_PasswordActionPerformed

    private void jTextField_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LoginActionPerformed

    private void jTextField_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_LoginMouseClicked
        LoginRegisterForm lrf = new LoginRegisterForm();
        lrf.setVisible(true);
        lrf.pack();
        lrf.setLocationRelativeTo(null);
        lrf.setDefaultCloseOperator(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jTextField_LoginMouseClicked

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CancelMouseExited
        //set jbutton background
        jButton_Cancel.setBackground(new Color(242,38,19));
    }//GEN-LAST:event_jButton_CancelMouseExited

/**/
    private void jButton_CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CancelMouseEntered
        //set jbutton background
        jButton_Cancel.setBackground(new Color(245,38,190));
    }//GEN-LAST:event_jButton_CancelMouseEntered

    private void jButton_CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CancelMouseClicked

    }//GEN-LAST:event_jButton_CancelMouseClicked

    private void jButton_SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SignupActionPerformed
        
        String username = jTextField_Username.getText();
        String pass1 = String.valueOf(jPasswordField_Password.getPassword());
        String pass2 = String.valueOf(jPasswordField_Confirm.getPassword());
        String email = jTextField_Email_Id.getText();
        String phone_no = jTextField_Phone_No.getText();
        String gender = "Male";
        SimpleDateFormat dateformat =  new SimpleDateFormat("yyyy-MM-dd");
        //String bdate;
        String bdate = "";
        String address = jTextArea_Address.getText();
        InputStream image = null;
        
        if(jRadioButton_Female.isSelected())
            gender = "Female";
        /*
        try {
            if(image_path != null)
                image = new FileInputStream(new File(image_path));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SignupForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        if(username.equals("username"))
            username = "";
        if(pass1.equals("password"))
            pass1 = "";
        if(pass2.equals("password"))
            pass2 = "";
        if(email.equals("email_id"))
            email = "";
        if(phone_no.equals("9999999999"))
            phone_no = "";
        
        try{
            bdate = dateformat.format(jDateChooser.getDate());
        }catch( NullPointerException ex){
            JOptionPane.showMessageDialog(null,"Date of Birth can't be Empty", "Empty Field", 2);
        }
        if(address.equals("Permanent Address"))
        {   address = "";
            System.out.println("address : "+address);
        }
        try
        {
            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 1099);
            
            SignupInterface i = (SignupInterface)reg.lookup("signup");
            
                
            // if fields are empty
            if( !i.verifyFields(username, pass1, pass2, email, phone_no, gender, bdate, address))
            {
                JOptionPane.showMessageDialog(null, "* Signup Form Fields can't be empty", "Empty Field", 2);   
            }
            else {   //( i.verifyFields(username, pass1, pass2, email, phone_no, gender, bdate, address)){
                if( !i.checkUsername(username)){
                    if( i.getSignup(username, pass1, email, phone_no, gender, bdate, image_path, address )  )
                            JOptionPane.showMessageDialog(null, "Your Account has been Created");
                }
            }
            
        }
        catch(Exception ex)
        {   System.out.println("pta ni error kya hai ");
            ex.printStackTrace();
        }
            
    }//GEN-LAST:event_jButton_SignupActionPerformed

    private void jButton_SignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SignupMouseExited
        //set jbutton background
        jButton_Signup.setBackground(new Color(0,84,104));

    }//GEN-LAST:event_jButton_SignupMouseExited

    private void jButton_SignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SignupMouseEntered
        //set jbutton background
        jButton_Signup.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_jButton_SignupMouseEntered

    private void jPasswordField_ConfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_ConfirmFocusLost
        //if the password field is equal to password or empty
        //we will set the "password" text in the field
        //on focus lost event

        //get the password text
        String pass = String.valueOf(jPasswordField_Confirm.getPassword());

        if(pass.equals("") ||
            pass.trim().equals("password"))
        {
            jPasswordField_Confirm.setText("password");
            jPasswordField_Confirm.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jPasswordField_ConfirmFocusLost

    private void jPasswordField_ConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_ConfirmFocusGained
        // clear the confirm password field on focus if the text is "password"

        //get the confirm password text
        String pass = String.valueOf(jPasswordField_Confirm.getPassword());

        if(pass.trim().toLowerCase().equals("password"))
        {
            jPasswordField_Confirm.setText("");
            jPasswordField_Confirm.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_ConfirmFocusGained

    private void jPasswordField_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordFocusLost
        //if the password field is equal to password or empty
        //we will set the "password" text in the field
        //on focus lost event

        //get the password text
        String pass = String.valueOf(jPasswordField_Password.getPassword());

        if(pass.equals("") ||
            pass.trim().equals("password"))
        {
            jPasswordField_Password.setText("password");
            jPasswordField_Password.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jPasswordField_PasswordFocusLost

    private void jPasswordField_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordFocusGained
        // clear the password field on focus if the text is "password"

        //get the password text
        String pass = String.valueOf(jPasswordField_Password.getPassword());

        if(pass.trim().toLowerCase().equals("password"))
        {
            jPasswordField_Password.setText("");
            jPasswordField_Password.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_PasswordFocusGained

    private void jTextField_Phone_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Phone_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Phone_NoActionPerformed

    private void jTextField_Phone_NoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Phone_NoFocusLost
        //if the text field is equal to username or empty
        //we will set the "username" text in the field
        //on focus lost event

        if(jTextField_Phone_No.getText().trim().equals("") ||
            jTextField_Phone_No.getText().trim().equals("9999999999"))
        {
            jTextField_Phone_No.setText("9999999999");
            jTextField_Phone_No.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_Phone_NoFocusLost

    private void jTextField_Phone_NoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Phone_NoFocusGained
        if(jTextField_Phone_No.getText().trim().equals("9999999999"))
        {
            jTextField_Phone_No.setText("");
            jTextField_Phone_No.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_Phone_NoFocusGained

    private void jTextField_Email_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Email_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Email_IdActionPerformed

    private void jTextField_Email_IdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Email_IdFocusLost
        //if the text field is equal to username or empty
        //we will set the "username" text in the field
        //on focus lost event

        if(jTextField_Email_Id.getText().trim().equals("") ||
            jTextField_Email_Id.getText().trim().equals("email_id"))
        {
            jTextField_Email_Id.setText("email_id");
            jTextField_Email_Id.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_Email_IdFocusLost

    private void jTextField_Email_IdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Email_IdFocusGained
        if(jTextField_Email_Id.getText().trim().toLowerCase().equals("email_id"))
        {
            jTextField_Email_Id.setText("");
            jTextField_Email_Id.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_Email_IdFocusGained

    private void jTextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UsernameActionPerformed

    private void jTextField_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusLost
        //if the text field is equal to username or empty
        //we will set the "username" text in the field
        //on focus lost event

        if(jTextField_Username.getText().trim().equals("") ||
            jTextField_Username.getText().trim().equals("username"))
        {
            jTextField_Username.setText("username");
            jTextField_Username.setForeground(new Color(153,153,153));
        }

    }//GEN-LAST:event_jTextField_UsernameFocusLost

    private void jTextField_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusGained
        if(jTextField_Username.getText().trim().toLowerCase().equals("username"))
        {
            jTextField_Username.setText("");
            jTextField_Username.setForeground(Color.black);
        }
        /*
        //set a black border to the jLabel icon
        Border jLabel_icon = BorderFactory.createMatteBorder(0, 1, 1, 1, new Color(153,153,153));
        jLabel_username.setBorder(jLabel_icon);
        */
    }//GEN-LAST:event_jTextField_UsernameFocusGained

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jTextArea_AddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea_AddressFocusGained
        if(jTextArea_Address.getText().trim().equals("Permanent Address")) 
        {
            jTextArea_Address.setText("");
            jTextArea_Address.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextArea_AddressFocusGained

    private void jTextArea_AddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea_AddressFocusLost
        //if the text field is equal to username or empty
        //we will set the "username" text in the field
        //on focus lost event

        if(jTextArea_Address.getText().trim().equals("") ||
            jTextArea_Address.getText().trim().equals("Permanent Address"))
        {
            jTextArea_Address.setText("Permanent Address");
            jTextArea_Address.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextArea_AddressFocusLost

    private void jRadioButton_FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_FemaleActionPerformed

    private void jTextField_Phone_NoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Phone_NoKeyTyped
        // allow only numbers
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_Phone_NoKeyTyped

    private void jButton_Select_ImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Select_ImageActionPerformed
        // select an image and set the image path into a jlabel
        String path = null;
        JFileChooser chooser = new JFileChooser();
        
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        // file extension 
        FileNameExtensionFilter extension = new FileNameExtensionFilter("Images",".jpg",".png", "jpeg");
        chooser.addChoosableFileFilter(extension);
        
        int filestate = chooser.showSaveDialog(null);
        
        // check if the userselect an image
        if(filestate == JFileChooser.APPROVE_OPTION){
            File selectedImage = chooser.getSelectedFile();
            path = selectedImage.getAbsolutePath();
            jLabel_Image_Path.setText(path);
            
            image_path = path;
        }
    }//GEN-LAST:event_jButton_Select_ImageActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Select_Image;
    private javax.swing.JButton jButton_Signup;
    private javax.swing.JCheckBox jCheckBox_Password;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_address;
    private javax.swing.JLabel jLabel1_dob;
    private javax.swing.JLabel jLabel1_dob1;
    private javax.swing.JLabel jLabel_Image_Path;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_confirm_password;
    private javax.swing.JLabel jLabel_email_id;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_phone_no;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JPasswordField jPasswordField_Confirm;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Address;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_Email_Id;
    private javax.swing.JTextField jTextField_Login;
    private javax.swing.JTextField jTextField_Phone_No;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables

    void setDefaultCloseOperator(int EXIT_ON_CLOSE) {
        
    }
}
